In [3]:
!pip3 install torch


In [2]:
import torch

In [6]:
# Create a 1d trensor
v = torch.tensor([1,2,3])

In [7]:
#  Print a tensor
print(v)

tensor([1, 2, 3])


In [8]:
# print data type of tensor
print(v.dtype)

torch.int64


In [10]:
# print value at a specific index
print(v[-1])

tensor(3)


In [11]:
v = torch.tensor([1,2,3,4,5,6])

In [17]:
# Slicing a tensor
print(v[0:3])
print(v[0:-1])
# note that first element is inclusive and the second element is exclusive

tensor([1, 2, 3])
tensor([1, 2, 3, 4, 5])


In [ ]:
# Create a float tensor
f = torch.Float